### ISSUE TITLE
请问能否代替siyuan的Tesseract，将识别内容，写入图片中的OCR识别内容部分

### ISSUE THREAD

**Issue by pisceswb** [zuoez02/siyuan-plugin-online-ocr#1]
请问能否代替siyuan的Tesseract，将识别内容，写入图片中的OCR识别内容部分，谢谢

**Comment by zuoez02** [comment]
目标就是增加除了本地的OCR，实现速度更快的OCR能力。后半句你说的是啥意思我没懂，不过OCR就是把本地的图片传到线上进行OCR解析。目前支持的是微软的api

**Comment by pisceswb** [comment]
抱歉没有说清楚，就是能否把插件在线识别的内容写入思源的图片OCR内容框中，如下图
![image](https://github.com/zuoez02/siyuan-plugin-online-ocr/assets/104658457/386b91df-2ad1-4afe-8ef0-33550c3d482b)

**Comment by zuoez02** [comment]
哦，不支持。插件的要在插件自己的界面中看。
我不是很喜欢思源自己的这个邮件设计。我自己设计了OCR的交互方案。你可以做到
1. 查看到OCR任务的状态，进行中、成功、失败
2. 对于成功的结果，可以直接复制所有内容，也可以点击查看详情，展示你OCR的图片并且在文字的位置框上了黄色外框方便你操作复制

**Comment by pisceswb** [comment]
哦，那我的需求可能不一样。我不是想复制图片中的内容，只想后台默默将图片识别成文字，后面搜索的时候能找到。
